### ISSUE TITLE
Move OffsetPaginatedListDto Client interface to an externally usable package

### ISSUE THREAD

**Issue by kyleroush** [cerner/beadledom#114]
### Step 1: Are you in the right place?

  * This is a feature request

### Step 2: Describe your environment
  * Beadledom version: 3.1

#### Expected Results:

  * I would like to have access to the interface for a paginated resource so that the client can implement it instead of having it be in the examples package 
https://github.com/cerner/beadledom/blob/3798bffbcd2de7e649eb55e81f2d2f5122e79d16/client/beadledom-client-example/example-api/src/main/java/com/cerner/beadledom/client/example/model/OffsetPaginatedListDto.java#L15 
 * Can we move this to the beadledom-client package so that clients can use it 
https://github.com/cerner/beadledom/tree/3798bffbcd2de7e649eb55e81f2d2f5122e79d16/client/beadledom-client

**Comment by johnlcox** [comment]
Fixed by #116
