### ISSUE TITLE
Allow configuration for http client retry

### ISSUE THREAD

**Issue by nathanschile** [cerner/beadledom#139]
Configuration of the number of retries that are tried should be configurable. Currently it is hard coded to 3.  

https://github.com/cerner/beadledom/blob/master/client/resteasy-client/src/main/java/com/cerner/beadledom/client/resteasy/BeadledomResteasyClientBuilder.java#L345-L348

**Comment by johnlcox** [comment]
Closing since the client was deprecated in #177
