### ISSUE TITLE
Improve details in the logs of the exception mapper

### ISSUE THREAD

**Issue by kyleroush** [cerner/beadledom#142]
# Step 3: Describe the problem:

## Steps to reproduce:

  1. An error is thrown
  2. The WebApplicationExceptionMapper logs and maps the request to a response 
  3. There might be no reference to what service the error was thrown from in the logs making it harder to search and find the logs

## Observed Results:

Right now the log starts with 
```
ERROR [qtp992217213-45] com.cerner.beadledom.jaxrs.exceptionmapping.ThrowableExceptionMapper An unhandled exception was thrown.
<STACK TRACE>
```
And if we have another interceptor that throws an error the stack trace will not reference the service code at all. 

## Expected Results:

I would like to have be able to have the logged message contain a cnfigurable `name` value so that the log can always reference the service that created the log

I would like to have an optional injected value to the exception mapper for the service name
or 
Inject the @Context so that the log can also reference the url the error is for

#### Relevant Code:
https://github.com/cerner/beadledom/blob/master/jaxrs/src/main/java/com/cerner/beadledom/jaxrs/exceptionmapping/WebApplicationExceptionMapper.java#L46

**Comment by nathanschile** [comment]
Hi Kyle.

You should be able to accomplish what you outline above by configuring your logging implementation (logback, log4j, ...) to include the name of your application. The logging configuration should be configured at runtime, so you could include your application name whereever you would like in the log message.
