### ISSUE TITLE
Bootstrap script doesn't handle redirects

### ISSUE THREAD

**Issue by b-boogaard** [cerner/beadledom#15]
With the redirects that happen for the doc site now the `install.sh` script fails when it tries to download `beadledom`.

Currently we aren't using the `-L` option when executing curl [1] which would allow curl to follow the redirects. We should use that.

We do have a restriction on the response code [2] between `200-299`. I'm not 100% but I think that range will still be fine if the `-L` option is provided to curl.

[1] https://github.com/cerner/beadledom/blob/master/archetype/bootstrap/bin/install.sh#L57]
[2] https://github.com/cerner/beadledom/blob/master/archetype/bootstrap/bin/install.sh#L65

**Comment by johnlcox** [comment]
Fixed by #17
