### ISSUE TITLE
Add JAX-RS PATCH annotation

### ISSUE THREAD

**Issue by johnlcox** [cerner/beadledom#21]
JAX-RS does not have a PATCH annotation for supporting HTTP patch method like it does for others like GET or POST. We should add a PATCH annotation that can be used for handling the patch HTTP method.

**Comment by b-boogaard** [comment]
+1 to this.

**Comment by nimeshsubramanian** [comment]
PR: https://github.com/cerner/beadledom/pull/36

**Comment by b-boogaard** [comment]
Merge to master: e83ff7ce05c6e0ddd9d9d1fe17b3c3a04a200cfc
