### ISSUE TITLE
Stagemonitor widget should be more locked down by default

### ISSUE THREAD

**Issue by johnlcox** [cerner/beadledom#25]
The current archetype doesn't provide any configuration around the stagemonitor widget [1]. The default configuration should be to have it locked down. Possibly with a comment or content updates in the documentation site on how the configuration could be changed for the widget.

[1] https://github.com/stagemonitor/stagemonitor/wiki/Only-show-the-widget-for-authorized-users

**Comment by lal-s** [comment]
Issue addressed in [b8de980](https://github.com/cerner/beadledom/commit/b8de980ccef38f94a974851641459ae4d857ee44)
