### ISSUE TITLE
Create a BOM to make consuming easier

### ISSUE THREAD

**Issue by bbaugher** [cerner/beadledom#30]
As a consumer it would be helpful if Beadledom provide a [BOM](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html) which provided the full list of dependencies so I don't have to include every beadledom library in my pom

**Comment by lal-s** [comment]
Issue address in [531f272](https://github.com/cerner/beadledom/commit/531f2726db4624526e969b9a69f90d73267fd00e)
