### ISSUE TITLE
Catch-All Exception Mapper

### ISSUE THREAD

**Issue by cbfshr** [cerner/beadledom#43]
I had a conversation with @johnlcox regarding possibly adding an exception mapper to Beadledom that will handle all uncaught exceptions in a service, map them, and return an error response in JSON format. This is similar to https://github.com/cerner/beadledom/issues/24, except that this issue is more about the exception mapper, which would utilize the format discussed in that issue.

The reason this came up was because all of our services which do not handle exceptions as they're thrown are sending responses in plain text with stack traces, and we don't have any real control over what gets sent back.

John proposed the exception mapper would be a class the implements `ExceptionMapper<Throwable>`.  An example of this is outlined in this article: http://www.codingpedia.org/ama/error-handling-in-rest-api-with-jersey/#22_Uncheckedtechnical_exceptions.

This would hopefully be a first step towards unifying our response structure across application services by implementing the catch all exception mapper with the proper JSON response. I'm opening this issue to discuss design/format/structure of the response, and any feedback is welcomed.

**Comment by johnlcox** [comment]
Fixed by 3ceffecc1f67cb5c4fa7a4cae51174571e6717ac
