### ISSUE TITLE
Client fails to deserialize java.time classes

### ISSUE THREAD

**Issue by bjtieman** [cerner/beadledom#47]
We have API models that use OffsetDataTime fields.  These are being serialized from the service side to strings as expected

...
"creationDate": "2017-09-06T19:21:15Z",
"lastModifiedDate": "2017-09-06T19:21:15Z"
...

however, when using the client to try to deserialize them we're seeing

javax.ws.rs.ProcessingException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `java.time.OffsetDateTime` (no Creators, like default construct, exist): no String-argument constructor/factory method to deserialize from String value ('2017-09-06T20:49:14.584Z')

I've tried following this documentation: http://engineering.cerner.com/beadledom/2.5.1/docs/manual/jackson.html to add com.fasterxml.jackson.datatype.jsr310.JavaTimeModule to try and add in the proper deseriaizer but it didn't work.  I'm a guice noob so maybe I'm doing something wrong?  Is there more explicit documentation on how to do this?  Or is there something else I'm doing wrong?

**Comment by johnlcox** [comment]
Can you post what your guice code is for registering that Jackson module for the client?

**Comment by bjtieman** [comment]
I basically copied the beadledom-health configuration from here:

https://github.com/cerner/beadledom/blob/master/health/service/src/main/java/com/cerner/beadledom/health/HealthModule.java#L116

I believe our service is indirectly picking up this registration which is allowing the service to serialize OffsetDateTime to a string as we'd expect.

public class ManagerClientModule extends AbstractModule {

    @Override
    protected void configure() {
        requireBinding(ManagerConfig.class);

        install(BeadledomClientModule.with(ManagerClientFeature.class));
        install(ObjectMapperClientFeatureModule.with(ManagerClientFeature.class));

        Multibinder<Module> jacksonModuleBinder = Multibinder.newSetBinder(binder(), Module.class);
        jacksonModuleBinder.addBinding().to(Jdk8Module.class);
        jacksonModuleBinder.addBinding().to(JavaTimeModule.class);
    }
...
}

Do we need to do something different on the client side...or am I just missing something obvious :(

**Comment by johnlcox** [comment]
On the client side you'll need to use an annotated multibinder that uses the same annotation you are using for the rest of your client Guice module. That annotation isolates all of the bindings from any other clients that might be used within the same consuming project.

```java
Multibinder<Module> jacksonModuleBinder = Multibinder
    .newSetBinder(binder(), Module.class, ManagerClientFeature.class);
```

**Comment by bjtieman** [comment]
Yep...that's what we were missing.  Thanks!
