### ISSUE TITLE
HealthChecker does not include exception in error message

### ISSUE THREAD

**Issue by bbaugher** [cerner/beadledom#68]
If a `HealthStatus` includes an exception it will not be logged out with the error message in `HealthChecker`. The issue is [here](https://github.com/cerner/beadledom/blob/83b527ccc44f26eb318aadc72ef1e0a5438bcfd7/health/service/src/main/java/com/cerner/beadledom/health/internal/HealthChecker.java#L130-L132). On this line it includes `status.getException()` at the end of the error method, but thats actually an `Optional< Throwable>`, so it is not being included since its not a `Throwable`.

**Comment by johnlcox** [comment]
Fixed by #98
