### ISSUE TITLE
WebApplicationExceptionMapper should value custom exception messages if present

### ISSUE THREAD

**Issue by venki09** [cerner/beadledom#69]
As of beadledom 2.7, the [WebApplicationExceptionMapper](https://github.com/cerner/beadledom/blob/2.7/jaxrs/src/main/java/com/cerner/beadledom/jaxrs/exceptionmapping/WebApplicationExceptionMapper.java) class constructs the exception message based on the status code's [reasonPhrase](https://github.com/cerner/beadledom/blob/2.7/jaxrs/src/main/java/com/cerner/beadledom/jaxrs/exceptionmapping/WebApplicationExceptionMapper.java#L64). I was wondering if this can be enhanced to support custom exception messages too. That way the consumer can get a better understanding of why that error was thrown instead of receiving the default reason phrase.

**Comment by johnlcox** [comment]
The built in exception mappers use the generic message because there is no guarantee that exception messages are safe to show to consumers of a service.

If you need to provide specific messages, then I would recommend creating custom exceptions and exception mappers.

**Comment by venki09** [comment]
Ah okay that makes sense. Just wanted to know the reason behind it. Thanks.
