### ISSUE TITLE
CorrelationIdClientHeader can cause conflicts with Guice

### ISSUE THREAD

**Issue by bbaugher** [cerner/beadledom#70]
* We are using two Beadledom clients in our service
 * Each client has its own annotation and uses the `BeadledomClientModule`
 * One client is in a private guice module and another is in a public/abstract guice module

This causes these kinds of conflicts,

```
1) A binding to com.google.common.base.Optional<com.google.inject.Provider<java.lang.String>> annotated with interface com.cerner.beadledom.client.CorrelationIdClientHeader was already configured at com.cerner.beadledom.client.BeadledomClientModule.configure(BeadledomClientModule.java:67) (via modules: com.cerner.pophealth.datamgmt.template.service.ConflictExample$MyPublicModule -> com.cerner.beadledom.client.BeadledomClientModule -> com.google.inject.multibindings.OptionalBinder$RealOptionalBinder).
  at com.cerner.beadledom.client.BeadledomClientModule.configure(BeadledomClientModule.java:67) (via modules: com.cerner.pophealth.datamgmt.template.service.ConflictExample$MyPrivateModule -> com.cerner.beadledom.client.BeadledomClientModule -> com.google.inject.multibindings.OptionalBinder$RealOptionalBinder)
```

[Here](https://gist.github.com/bbaugher/55bd51a68be71973169fc6467c024cc8) is an example in a unit test that demonstrates this behavior.

From my sparse understanding of Guice, it seems like Guice doesn't like that the public/root environment has a definition of this correlation header and the private module/space has its own definition, with the private module having both definitions available to it.

This is interesting because I would have imagined this shouldn't happen since everything is namespaced by the annotation used. This is true for all/most things in `BeadledomClientModule` except the correlation header since this is actually a `String` with the annotation `CorrelationIdClientHeader`.

Worth noting you don't have any problem if both of these clients are in the same public module or public guice space/environment.

I understand this setup is a bit particular but thought it was worth mentioning.

**Comment by johnlcox** [comment]
I wonder if `OptionalBinder` cannot cross injector boundaries similarly to the restriction on `Multibinder` as mentioned [here](https://groups.google.com/forum/#!topic/google-guice/h70a9pwD6_g).

I wrote a couple test and it seems like this is probably the case. This would mean the `BeadledomClientModule` must always be installed within public modules at the same injector level as where the correlation ID header name value is configured. Private modules create child-injectors and this seems likely to be the issue.

I would think you could still technically have multiple clients installed each in private module so long as the private module also provides the correlation id header name configuration. This would allow configuring different correlation id header names for different clients if necessary.

**Comment by johnlcox** [comment]
Closing since a solution was documented in the 3.0 release and the client was deprecated in #177
