### ISSUE TITLE
Recommended client module can cause unwanted behavior in service

### ISSUE THREAD

**Issue by bbaugher** [cerner/beadledom#71]
The [current recommended way from beadledom](https://github.com/cerner/beadledom/blob/master/archetype/simple-service/src/main/resources/archetype-resources/client/src/main/java/client/__name__ClientModule.java) to create the client module is to expose the client resource classes. If you consume another client module like this in your Beadledom service without wrapping it in a `PrivateModule` to ensure the resource classes are not exposed they will end up being served by Resteasy/JAXRS.

Wrapping these client modules in a `PrivateModule` is fairly trivial but not intuitive. Its easy to forget the magic that is JAXRS which will interrogate Guice's environment for any JAXRS providers it finds. We ran into this and only discovered this issue after looking at our swagger doc and noticing endpoints that were not ours.

I've seen others create a POJO client that takes in the `BeadledomClient` and provides get methods for all the resource classes. Then they only expose this POJO client instead of the resource classes themselves.

This is mostly to start discussion on this to see if theres a fix worth doing here or if service developers just need to understand this.

**Comment by johnlcox** [comment]
Give the issues discovered around `PrivateModule` and `OptionalBinder` in #70 it seems like the current recommendation for creating client Guice modules is flawed in multiple ways.

First we likely should change the archetype to use `AbstractModule` for the client Guice modules. This will help some of #70, but we'll also likely want some additional documentation around configuring the correlation ID header name for clients.

Second we should determine guidance on how to avoid client JAX-RS resources being registered with the JAX-RS server when client's are used within a server. I think there are 2 approaches to this.

1. Provide a wrapper class like `GithubClient` that has methods on it for getting access to each of the client `JAX-RS` resources.
1. Recommend and documents (both in the archetypes and the site) a more structured approached to the server side Guice modules. This could include a sort of bootstrap modules that sets up Beadledom and Resteasy followed by a service module that is private but installs everything else, including clients, and only exposes the JAX-RS resources and filters that should be used by the server. We have actually done something sort of like this on one of our services and it's pretty nice compared to having one giant Guice module for the server bindings.

**Comment by johnlcox** [comment]
I updated the archetype and getting started guide in the 3.x-doc-archtype branch [1]. Are there any other places I should make changes to provide clarity on the recommended usage and creation of client modules?

[1] https://github.com/cerner/beadledom/compare/3.x...3.x-doc-archtype

**Comment by bbaugher** [comment]
No that looks great, thanks!

**Comment by johnlcox** [comment]
Closing since a solution was documented in the 3.0 release and the client was deprecated in #177
