### ISSUE TITLE
Add New Relic Ignore Transaction Support

### ISSUE THREAD

**Issue by nathanschile** [cerner/beadledom#85]
We have a use case where we want to ignore certain transactions from being sent to [New Relic](https://newrelic.com/). New Relic support several ways to [ignore a transaction](https://docs.newrelic.com/docs/agents/java-agent/instrumentation/ignore-transactions-using-api). Since not all consumer will have access to the modules they are installing, having a request filter to ignore requests that match a URI pattern seems like a good approach. 

If the request filter is the desired approach, how should the consumers configure the paths they want excluded? Some options are an [Ant path pattern](http://ant.apache.org/manual/dirtasks.html#patterns) used within Maven and [Stagemonitor](https://github.com/stagemonitor/stagemonitor/wiki/Configuration-Options#excluded-paths-ant-path-style-1). Another option would be [Java regex pattern](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html). 

To exclude anything under the `/meta/` path. The Ant pattern would be `/meta/**` while the regex would be `^/meta//?.*`. Thoughts?

**Comment by johnlcox** [comment]
@nathanschile Did you figure out a way to filter the transactions through New Relic?
