### ISSUE TITLE
[enhancement-request] beadledom-client should provide health resource

### ISSUE THREAD

**Issue by venki09** [cerner/beadledom#88]
It would be nice if beadledom-client exposes a HealthResource by default so that the consumers of that client can use it to check the health of their dependencies. Currently all the clients write a HealthResource themselves and expose it which I think can be avoided if beadledom provides it off the shelf.

**Comment by johnlcox** [comment]
While it isn't bound by default, each client shouldn't need to write a `HealthResource`. Clients that want to make the health check part of the client API can just bind the specific `beadledom-health-api` [1] resources they would like to make available, just like any of their own resources.

[1] https://github.com/cerner/beadledom/tree/master/health/api/src/main/java/com/cerner/beadledom/health/api
