### ISSUE TITLE
Consumed version of Stage Monitor relies on version of p6spy with defective POM

### ISSUE THREAD

**Issue by winder487** [cerner/beadledom#92]
[WARNING] Invalid POM for p6spy:p6spy:jar:2.2.0, transitive dependencies (if any) will not be available, enable debug logging for more details

See issue https://github.com/p6spy/p6spy/issues/300 for more details

**Comment by johnlcox** [comment]
Closing since stagemonitor is being removed in the upcoming 4.0 release.
